#:schema node_modules/wrangler/config-schema.json
name = "workers-ai-image"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "4ac0b746b08802bf977c72884ae6adf8"
